# Generated by Django 6.1.1 on 2026-09-09 19:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('active_processes', models.IntegerField(default=0)),
                ('labor_risk', models.CharField(default='Baixo', max_length=50)),
                ('environmental_situation', models.CharField(default='Regular', max_length=100)),
                ('score_nortedue', models.IntegerField(default=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monitored_by', models.ManyToManyField(blank=True, related_name='monitored_suppliers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
